document.write("<br/>Button Text:  ");
document.write(document.getElementById('Button_2').value);
document.write("<br/>Node Name:  ");
document.write(document.getElementById('Button_2').nodeName);
document.write("<br/>ID:  ");
document.write(document.getElementById('Button_2').id);
document.write("<br/>Node Value:  ");
document.write(document.getElementById('Button_2').nodeValue);
document.write("<br/>Last Child:  ");
document.write(document.getElementById('Button_2').lastChild);
document.write("<br/>First Child:  ");
document.write(document.getElementById('Button_2').firstChild);
document.write("<br/>Parent Node:  ");
document.write(document.getElementById('Button_2').parentNode);
document.write("<br/>Parent Node ID:  ");
document.write(document.getElementById('Button_2').parentNode.id);
document.write("<br/>Parent Node attribute[0]:  ");
document.write(document.getElementById('Button_2').parentNode.attributes[0]);
document.write("<br/>Attributes[0] Node Type:  ");
document.write(document.getElementById('Button_2').attributes[0].nodeType);
document.write("<br/>Parent Node's Child Nodes[0]:  ");
document.write(document.getElementById('Button_2').parentNode.childNodes[0]);
document.write("<br/>Parent Node's Child Nodes[1]:  ");
document.write(document.getElementById('Button_2').parentNode.childNodes[1]);
document.write("<br/>Parent Node's Child Nodes[2]:  ");
document.write(document.getElementById('Button_2').parentNode.childNodes[2]);
document.write("<br/>Parent Node's Child Nodes[3]:  ");
document.write(document.getElementById('Button_2').parentNode.childNodes[3]);
document.write("<br/>Parent Node's Child Nodes[4]:  ");
document.write(document.getElementById('Button_2').parentNode.childNodes[4]);
document.write("<br/>Parent Node's Child Nodes[5]:  ");
document.write(document.getElementById('Button_2').parentNode.childNodes[5]);
document.write("<br/>Parent Node's Child Nodes[6]:  ");
document.write(document.getElementById('Button_2').parentNode.childNodes[6]);